### ISSUE TITLE
Support alternative system.configs

### ISSUE THREAD

**Issue by marshallswain** [donejs/done-ssr-middleware#11]
I'd like to come up with an API to support alternative configurations.  This would be useful when you want to SSR-load a different main for non-authenticated/public users, for example.  I'd like to see something where you could provide keyed configs in an object like this:

```js
var configs = {
  public: {
	  config: process.cwd() + '/public/package.json!npm',
	  bundle: 'feathers-chat/public.stache!done-autorender',
	  liveReload: true
  },
  app: {
	  config: process.cwd() + '/public/package.json!npm',
	  liveReload: true
  }
};
```

I'm thinking that this would create a renderer for each config, and render would actually be an object keyed the same way, so you could provide a function to select which renderer.

```js
selectRenderer(req){
  if (req.hasValidCookie) {
    return 'app';
  } else {
    return 'public';
  }
}
```

Then the code here could be modified to look like this:
```js
return function (req, res, next) {
  var stream = render[selectRenderer(req)](req);
  stream.on("error", next);
  stream.pipe(res);
  res.type("html");
};
```

I think this API would allow flexibility to do as many alternative configurations as desired.

But now the big question is, can we make it work so that it conditionally loads a different bundle from the package.json?

**Comment by marshallswain** [comment]
And we'd want to come up with a way to make it so the current API continues to work.

**Comment by justinbmeyer** [comment]
> This would be useful when you want to SSR-load a different main for non-authenticated/public users, 

Why would you want to do that?  In general, you'd want the single main's logic to switch between pages if the user is logged in or not.  I think bitballs does something like this.

I think what you want is already supported.  You can call `ssr` with different configs.  You'd have two `ssr` renderer functions you could call on your own.  This might not be working right now, but the APIs already support it:

```
ssr1 = ssr({
      config: process.cwd() + '/public/package.json!npm',
      bundle: 'feathers-chat/public.stache!done-autorender',
      liveReload: true
  })

ssr2 = ssr({
      config: process.cwd() + '/public/package.json!npm',
      liveReload: true
  })

return function (req, res, next) {
  var stream = selectRenderer(req, ssr1, ssr2)(req);
  stream.on("error", next);
  stream.pipe(res);
  res.type("html");
};
```

**Comment by marshallswain** [comment]
The main app is much simpler when it can assume that it already has valid auth.  I'm using progressive enhancement on the public-facing app, so it assumes no auth until it has a chance to check the validity of the token on the client.

The only way I can see this working currently is to provide a separate package.json with a different main.

**Comment by justinbmeyer** [comment]
Why a separate package.json?

**Comment by justinbmeyer** [comment]
You can specify the main with ssr. Couldn't you use one package.json and specify different mains?

**Comment by marshallswain** [comment]
I tried passing my other stache file as the main, but it still loads the main specified in the package.json.

**Comment by marshallswain** [comment]
In the package.json, my main is set to `feathers-chat/index.stache!done-autorender`.  I tried changing the main like shown below, and it still loads the main.
```
app.use('/', ssr({
  config: process.cwd() + '/public/package.json!npm',
  main: 'feathers-chat/public.stache!done-autorender',
  liveReload: true
}));
```

**Comment by justinbmeyer** [comment]
That's a bug then.  What's passed to `ssr` should basically be a system.config object and be applied the same way steal applies settings.

**Comment by marshallswain** [comment]
Hmmm.. Looks like it actually gets passed directly to `steal.config` here: https://github.com/donejs/done-ssr/blob/master/lib/index.js#L39.

**Comment by matthewp** [comment]
Can you submit a breaking test?  Actually all of our tests in done-ssr use a single package.json and work by passing different mains, so I have a hard time thinking of how this bug is happening to you.

**Comment by marshallswain** [comment]
I actually reworked everything to use a single config and still work really great.  I'm going to close this unless/until I run into the need to look at it again.
