### ISSUE TITLE
Allow getting the main from pkg.steal

### ISSUE THREAD

**Issue by matthewp** [donejs/done-ssr-middleware#16]
This looks for `pkg.system` only: https://github.com/donejs/done-ssr-middleware/blob/master/lib/index.js#L23

**Comment by matthewp** [comment]
@phillipskevin This is one of the issues with production (but not the only one I believe).

**Comment by phillipskevin** [comment]
This is fixed in done-ssr-middleware v1.0.0-alpha.2.
